version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - 3306:3306
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_USER: &db_user app
      MARIADB_DATABASE: &db app
      MARIADB_PASSWORD: &db_pass apppass
      MARIADB_ROOT_PASSWORD: &root_pass rootpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: *root_pass
  
  app:
    tty: true
    image: 'app:latest'
    build: .
    labels:
      kompose.service.type: nodeport
    environment:
      DB_HOST: mariadb
      DB_USERNAME: *db_user
      DB_DATABASE: *db
      DB_PASSWORD: *db_pass
    depends_on:
      - mariadb
    ports:
      - 8182:80
    volumes:
      - /mnt/d/dockerdata/web-hosting/public_html:/var/www/html
